name: gitHub_workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print a statement 1
        run: echo "Hello World from GitHub Actions!"
      - name: print a statement 2
        run: echo "Good Evening"
  second-job: 
    runs-on: ubuntu-latest
    steps:
        - name: print statement 3
          run: echo "today date is 10-12-25"
        - name: print statement 4
          run: echo "toady is wednesday"

        
